#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Jun 03, 2022 10:58:40 PM CST  platform: Windows NT

import tkinter as tk
from tkinter import filedialog, messagebox
import mw

root = None
_top1 = None
_w1 = None


def dir_open():
    fd = filedialog.askopenfilename(filetypes=[('哈希表文件', (".htf", ".hash")), ("哈希表数据库", (".hst", ".hdb")), ("所有文件", "*.*")])
    if fd == "":
        if messagebox.askretrycancel(title="文件错误", message="我们在打开文件时遇到错误。\n原因：未选择"):
            dir_open()
        else:
            raise
    else:
        return fd


def main():
    """Main entry point for the application."""
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    file = dir_open()
    global _top1, _w1
    _top1 = root
    _w1 = mw.Toplevel1(_top1, hash_file=file)
    root.mainloop()


def search_key_word(kw: str, hashfile: dict):
    for i in hashfile.values():
        for j in i.values():
            if j == kw:
                return i
    return False


def search_id(kw: int, hashfile: dict):
    try:
        res = hashfile[int(kw)]
        print("aa", res)
    except KeyError:
        return False
    return res


if __name__ == '__main__':
    mw.start_up()
